name: tasmarttoilet
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  curved_navigation_bar: ^1.0.3
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.3.2
  flutter_svg: ^2.0.7
  image_picker: ^1.0.4
  flutter_animated_dialog: ^2.0.1
  firebase_auth: ^4.10.0
  http: ^1.1.0
  intl: ^0.18.1
  provider: ^6.0.5
  firebase_core: ^2.16.0
  firebase_database: ^10.2.6
  firebase_storage: ^11.2.7
  fluttertoast: ^8.2.2
  ndialog: ^4.3.1
  # cloud_firestore:

flutter_native_splash:
  background_image: "images/splashfix.jpg"

  android: true

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - images/

  fonts:
    - family: SansPro
      fonts:
        - asset: fonts/SourceSansPro-Regular.ttf
        - asset: fonts/SourceSansPro-Bold.ttf
          weight: 400
